"""Private durable idempotency receipts for :class:`OperationRunner`.

The store deliberately keeps external-send attempts separate from committed
results.  If a process loses the connection after an external send, a retry
finds the attempt marker and fails closed instead of silently sending twice.
"""

from __future__ import annotations

from dataclasses import asdict
from datetime import UTC, datetime
import json
import os
from pathlib import Path
import sqlite3

from ._storage import connect_sqlite_store
from .discord_blogger_contract import canonical_json_bytes, canonical_json_sha256
from .models import OperationResult, OperationSpec, OperationStatus


class ReceiptConflict(RuntimeError):
    """An idempotency key was reused with a different canonical spec."""


class UncommittedReceipt(RuntimeError):
    """An earlier attempt exists but has no safely replayable result."""


WORKER_CONTEXT_KEY = "_omni_worker_context"


def canonical_operation_spec_sha256(spec: OperationSpec) -> str:
    """Hash only execution semantics, excluding per-invocation metadata."""

    retry = asdict(spec.retry_policy)
    payload = dict(spec.payload)
    worker_context = payload.get(WORKER_CONTEXT_KEY)
    if isinstance(worker_context, dict):
        # A reclaimed TaskQueue lease must replay the receipt generated by its
        # predecessor.  Worker identity, epoch, and fencing suffix are
        # authoritative execution metadata, not different user work.
        payload[WORKER_CONTEXT_KEY] = {
            key: worker_context.get(key)
            for key in ("trace_id", "idempotency_key", "task_id")
        }
    execution_spec = {
        "name": spec.name,
        "action": spec.action,
        "connector": spec.connector,
        "payload": payload,
        "actor": spec.actor,
        "source": spec.source,
        "risk_level": spec.risk_level.code,
        "required_permissions": spec.required_permissions,
        "approval_required": spec.approval_required,
        "sandbox_required": spec.sandbox_required,
        "timeout_seconds": spec.timeout_seconds,
        "retry_policy": retry,
        "dry_run": spec.dry_run,
    }
    return canonical_json_sha256(execution_spec)


class OperationReceiptStore:
    """SQLite receipt store keyed by ``(operation_name, idempotency_key)``."""

    def __init__(self, db_path: Path | str) -> None:
        self.db_path = Path(db_path).resolve()
        self.db_path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        try:
            os.chmod(self.db_path.parent, 0o700)
        except OSError:
            pass
        self._init_schema()
        try:
            os.chmod(self.db_path, 0o600)
        except OSError:
            pass

    def lookup(
        self,
        operation_name: str,
        idempotency_key: str,
        spec_sha256: str,
    ) -> OperationResult | None:
        """Compatibility wrapper for a non-reserving atomic acquire."""

        return self.acquire(
            operation_name,
            idempotency_key,
            spec_sha256,
            external_send=False,
            reserve=False,
        )

    def acquire(
        self,
        operation_name: str,
        idempotency_key: str,
        spec_sha256: str,
        *,
        external_send: bool,
        reserve: bool,
    ) -> OperationResult | None:
        """Atomically replay, reject a collision, or reserve an unused key.

        With ``reserve=False`` an unused key is only inspected.  With
        ``reserve=True`` the same transaction inserts the started receipt and
        external-send attempt marker.  A concurrent committer that wins the
        writer lock is therefore observed as a replay, never as the old
        lookup/begin false-uncommitted race.
        """

        now = datetime.now(UTC).isoformat()
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            row = conn.execute(
                """
                SELECT spec_sha256, state, result_json
                FROM operation_receipts
                WHERE operation_name = ? AND idempotency_key = ?
                """,
                (operation_name, idempotency_key),
            ).fetchone()
            if row is not None:
                self._require_matching_hash(row["spec_sha256"], spec_sha256)
                if row["state"] != "committed" or row["result_json"] is None:
                    raise UncommittedReceipt(
                        "idempotent operation attempt already recorded without a "
                        "committed result; manual reconciliation is required"
                    )
                result = _result_from_json(row["result_json"])
                conn.commit()
                return result
            if not reserve:
                conn.commit()
                return None
            conn.execute(
                """
                INSERT INTO operation_receipts (
                    operation_name, idempotency_key, spec_sha256, state,
                    result_json, created_at, committed_at
                ) VALUES (?, ?, ?, 'started', NULL, ?, NULL)
                """,
                (operation_name, idempotency_key, spec_sha256, now),
            )
            if external_send:
                conn.execute(
                    """
                    INSERT INTO operation_send_attempts (
                        operation_name, idempotency_key, spec_sha256, attempted_at
                    ) VALUES (?, ?, ?, ?)
                    """,
                    (operation_name, idempotency_key, spec_sha256, now),
                )
            conn.commit()
        return None

    def begin(
        self,
        operation_name: str,
        idempotency_key: str,
        spec_sha256: str,
        *,
        external_send: bool,
    ) -> None:
        """Compatibility wrapper for a reserving atomic acquire."""

        self.acquire(
            operation_name,
            idempotency_key,
            spec_sha256,
            external_send=external_send,
            reserve=True,
        )

    def commit(
        self,
        operation_name: str,
        idempotency_key: str,
        spec_sha256: str,
        result: OperationResult,
    ) -> None:
        """Atomically attach a canonical committed result to a reserved key."""

        result_json = canonical_json_bytes(result.to_dict()).decode("utf-8")
        now = datetime.now(UTC).isoformat()
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            existing = conn.execute(
                """
                SELECT spec_sha256, state, result_json
                FROM operation_receipts
                WHERE operation_name = ? AND idempotency_key = ?
                """,
                (operation_name, idempotency_key),
            ).fetchone()
            if existing is None:
                conn.rollback()
                raise UncommittedReceipt("operation receipt was not reserved")
            self._require_matching_hash(existing["spec_sha256"], spec_sha256)
            if existing["state"] == "committed":
                if existing["result_json"] != result_json:
                    conn.rollback()
                    raise ReceiptConflict(
                        "committed idempotency receipt cannot be overwritten"
                    )
                conn.commit()
                return
            conn.execute(
                """
                UPDATE operation_receipts
                SET state = 'committed', result_json = ?, committed_at = ?
                WHERE operation_name = ? AND idempotency_key = ?
                  AND spec_sha256 = ? AND state = 'started'
                """,
                (
                    result_json,
                    now,
                    operation_name,
                    idempotency_key,
                    spec_sha256,
                ),
            )
            conn.commit()

    def has_send_attempt(
        self,
        operation_name: str,
        idempotency_key: str,
        spec_sha256: str,
    ) -> bool:
        with self._connect() as conn:
            row = conn.execute(
                """
                SELECT spec_sha256 FROM operation_send_attempts
                WHERE operation_name = ? AND idempotency_key = ?
                """,
                (operation_name, idempotency_key),
            ).fetchone()
        if row is None:
            return False
        self._require_matching_hash(row["spec_sha256"], spec_sha256)
        return True

    def _init_schema(self) -> None:
        with self._connect() as conn:
            conn.executescript(
                """
                PRAGMA synchronous = FULL;
                PRAGMA foreign_keys = ON;

                CREATE TABLE IF NOT EXISTS operation_receipts (
                    operation_name TEXT NOT NULL,
                    idempotency_key TEXT NOT NULL,
                    spec_sha256 TEXT NOT NULL,
                    state TEXT NOT NULL CHECK (state IN ('started', 'committed')),
                    result_json TEXT,
                    created_at TEXT NOT NULL,
                    committed_at TEXT,
                    PRIMARY KEY (operation_name, idempotency_key),
                    CHECK (
                        (state = 'started' AND result_json IS NULL AND committed_at IS NULL)
                        OR
                        (state = 'committed' AND result_json IS NOT NULL
                         AND committed_at IS NOT NULL)
                    )
                );

                CREATE TABLE IF NOT EXISTS operation_send_attempts (
                    operation_name TEXT NOT NULL,
                    idempotency_key TEXT NOT NULL,
                    spec_sha256 TEXT NOT NULL,
                    attempted_at TEXT NOT NULL,
                    PRIMARY KEY (operation_name, idempotency_key),
                    FOREIGN KEY (operation_name, idempotency_key)
                        REFERENCES operation_receipts(operation_name, idempotency_key)
                        ON DELETE RESTRICT
                );
                """
            )
            conn.commit()

    def _connect(self) -> sqlite3.Connection:
        conn = connect_sqlite_store(self.db_path)
        conn.execute("PRAGMA synchronous = FULL")
        conn.execute("PRAGMA foreign_keys = ON")
        return conn

    @staticmethod
    def _require_matching_hash(stored: str, supplied: str) -> None:
        if stored != supplied:
            raise ReceiptConflict(
                "idempotency key collision: canonical operation spec differs"
            )


def _result_from_json(raw: str) -> OperationResult:
    value = json.loads(raw)
    if not isinstance(value, dict):
        raise ValueError("operation receipt result must be a JSON object")
    return OperationResult(
        operation_id=str(value["operation_id"]),
        status=OperationStatus(str(value["status"])),
        output=dict(value.get("output", {})),
        error=value.get("error"),
        policy_reason=value.get("policy_reason"),
        audit_id=value.get("audit_id"),
        trace_id=str(value.get("trace_id", "")),
    )
