#!/usr/bin/env python3
"""Daily multi-target follow brief.

Runs ``follow_person`` and ``follow_company`` over a hand-picked watchlist
and writes one consolidated markdown brief per day under
``.omni/briefs/follow-YYYY-MM-DD.md``.

Designed to be invoked by the ``com.omni-hub.daily-follow`` launchd agent
once a day (default 08:30 local).  Subprocess-isolates each follow call
so any single profile/source failure can't kill the brief.

Override the watchlist via env vars::

    DAILY_FOLLOW_PEOPLE="karpathy,altman,dario"  \\
    DAILY_FOLLOW_COMPANIES="anthropic,openai,nvidia" \\
        python3 scripts/daily_follow_brief.py

Default watchlist below is biased to AI research + leadership signals.
"""

from __future__ import annotations

import os
import subprocess
import sys
from datetime import date
from pathlib import Path


DEFAULT_PEOPLE = [
    "karpathy", "altman", "dario", "ilya", "huang",
    "dwarkesh", "simonw", "lilianweng",
]
DEFAULT_COMPANIES = [
    "anthropic", "openai", "deepmind", "xai",
    "nvidia", "deepseek",
]
# Sources to pass to follow_person/follow_company.  Skip GDELT here —
# its retry/cache helps but it's still the flakiest source; cron-grade
# briefs do better without it.
DEFAULT_PERSON_SOURCES = "rss,hn,openalex,tavily"
DEFAULT_COMPANY_SOURCES = "rss,hn,tavily,edgar"


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _run_follow(kind: str, target: str, sources: str, limit: int) -> str:
    """Invoke the appropriate follow script in a subprocess.  Returns
    its stdout (markdown).  Captures + suppresses stderr to keep the
    brief clean; failures yield an empty section.
    """

    script_name = "follow_person.py" if kind == "person" else "follow_company.py"
    script = _repo_root() / "scripts" / script_name
    cmd = [
        sys.executable, str(script), target,
        "--sources", sources,
        "--limit", str(limit),
    ]
    try:
        out = subprocess.run(
            cmd, capture_output=True, text=True, timeout=120, check=False,
        )
        return out.stdout or f"_(no output: rc={out.returncode})_\n"
    except subprocess.TimeoutExpired:
        return f"_(timeout after 120s following {kind}: {target})_\n"
    except Exception as exc:                                       # noqa: BLE001
        return f"_(error: {type(exc).__name__}: {exc})_\n"


def _split_env(name: str, default: list[str]) -> list[str]:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    return [s.strip() for s in raw.split(",") if s.strip()]


def main() -> int:
    today = date.today().isoformat()
    out_dir = _repo_root() / ".omni" / "briefs"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"follow-{today}.md"

    people = _split_env("DAILY_FOLLOW_PEOPLE", DEFAULT_PEOPLE)
    companies = _split_env("DAILY_FOLLOW_COMPANIES", DEFAULT_COMPANIES)
    person_sources = os.environ.get("DAILY_FOLLOW_PERSON_SOURCES", DEFAULT_PERSON_SOURCES)
    company_sources = os.environ.get("DAILY_FOLLOW_COMPANY_SOURCES", DEFAULT_COMPANY_SOURCES)
    limit = int(os.environ.get("DAILY_FOLLOW_LIMIT", "3"))

    sections: list[str] = [
        f"# Daily follow brief — {today}\n",
        f"_Generated by `daily_follow_brief.py` at "
        f"`{out_path.relative_to(_repo_root())}`_\n",
    ]

    sections.append(f"\n# People ({len(people)})\n")
    for p in people:
        sys.stderr.write(f"→ person: {p}\n")
        sections.append(_run_follow("person", p, person_sources, limit))
        sections.append("\n---\n")

    sections.append(f"\n# Companies ({len(companies)})\n")
    for c in companies:
        sys.stderr.write(f"→ company: {c}\n")
        sections.append(_run_follow("company", c, company_sources, limit))
        sections.append("\n---\n")

    out_path.write_text("\n".join(sections), encoding="utf-8")
    sys.stderr.write(f"\n✅ brief written: {out_path}\n")
    print(str(out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
